### Pre-Requisites

In [6]:
#!pip install folium
#!pip install gpxpy

In [10]:
import gpxpy
import gpxpy.gpx

import pandas as pd

import folium

### Load your GPX Data

In [3]:
with open('My_Routes/PL-SK-HU.gpx', 'r') as gpx_file:
    gpx = gpxpy.parse(gpx_file)

route_info = []

for track in gpx.tracks:
    for segment in track.segments:
        for point in segment.points:
            route_info.append({
                'latitude': point.latitude,
                'longitude': point.longitude,
                'elevation': point.elevation
            })

route_df = pd.DataFrame(route_info)
route_df.head()

    latitude  longitude   elevation
0  49.864104  19.109029  386.362446
1  49.864275  19.109137  386.362446
2  49.864374  19.109211  386.362446
3  49.864470  19.109280  386.362446
4  49.864582  19.109354  386.362446

In [15]:
# #!pip install folium

# import folium


# route_map = folium.Map(
#     location=[45, 25.3],
#     zoom_start=5,
#     tiles='OpenStreetMap',
#     width=1024,
#     height=600
# )

# coordinates = [tuple(x) for x in route_df[['latitude', 'longitude']].to_numpy()]
# folium.PolyLine(coordinates, weight=6).add_to(route_map)

# display(route_map)

### Convert GPX to JSON

In [3]:
# !pip install gpx_converter

from gpx_converter import Converter

import json

df_dict = Converter(input_file='./HU-GR_gpx/HU-GR.gpx').gpx_to_dictionary(latitude_key='latitude', longitude_key='longitude')

In [11]:
df_dict

print(type(df_dict))

<class 'dict'>

In [12]:
 list(df_dict.keys())

['time', 'latitude', 'longitude', 'altitude']

### Visualize & Save a route (GPX) with Folium and OpenStreetMaps

In [17]:
# with open('HU-GR_gpx/HU-GR.gpx', 'r') as gpx_file:
#     gpx = gpxpy.parse(gpx_file)

with open('My_Routes/PL-SK-HU.gpx', 'r') as gpx_file:
    gpx = gpxpy.parse(gpx_file)

In [18]:
route_info = []

for track in gpx.tracks:
    for segment in track.segments:
        for point in segment.points:
            route_info.append({
                'latitude': point.latitude,
                'longitude': point.longitude,
                'elevation': point.elevation
            })

route_df = pd.DataFrame(route_info)
#route_df.head()

In [19]:
route_map = folium.Map(
    location=[47, 32],
    zoom_start=5,
    tiles='OpenStreetMap',
    width=924,
    height=600
)

coordinates = [tuple(x) for x in route_df[['latitude', 'longitude']].to_numpy()]
folium.PolyLine(coordinates, weight=3).add_to(route_map)
folium.LayerControl().add_to(route_map)

display(route_map)

#route_map.save('./output_map.html')

In [20]:
#Will be saved in the current folder with the specified name below
#route_map.save('./output_map.html')

### Visualize & Save a route (Geo JSON) with Folium and OpenStreetMaps

In [21]:
route_df[['latitude', 'longitude']].to_numpy()

array([[49.864104, 19.109029],
       [49.864275, 19.109137],
       [49.864374, 19.109211],
       ...,
       [47.500879, 19.054692],
       [47.500976, 19.0547  ],
       [47.500983, 19.054714]])

In [32]:
# print(df_dict.get('latitude'))
# print(df_dict.get('longitude'))

[df_dict.get('latitude'),df_dict.get('longitude')]

[[47.634836,
  47.634213,
  47.632601,
  47.632461,
  47.632335,
  47.632,
  47.631965,
  47.631936,
  47.631737,
  47.631607,
  47.631135,
  47.629714,
  47.629299,
  47.628563,
  47.627728,
  47.626902,
  47.626541,
  47.625977,
  47.625911,
  47.625796,
  47.625826,
  47.62601,
  47.626045,
  47.625854,
  47.625552,
  47.625476,
  47.624975,
  47.624715,
  47.623783,
  47.62339,
  47.622314,
  47.621602,
  47.620335,
  47.620324,
  47.62022,
  47.619866,
  47.619749,
  47.619644,
  47.619604,
  47.619572,
  47.619439,
  47.619061,
  47.618976,
  47.618928,
  47.618808,
  47.618763,
  47.618529,
  47.618357,
  47.617866,
  47.617665,
  47.617552,
  47.617461,
  47.617314,
  47.617125,
  47.616982,
  47.616575,
  47.615677,
  47.615443,
  47.614974,
  47.614438,
  47.614418,
  47.614263,
  47.614117,
  47.613552,
  47.613339,
  47.613303,
  47.612056,
  47.611951,
  47.611207,
  47.611061,
  47.611049,
  47.611014,
  47.610965,
  47.610083,
  47.609411,
  47.609159,
  47.608722,
  47.60793,
  47.6077,
  47.607429,
  47.606921,
  47.606898,
  47.606871,
  47.606735,
  47.606663,
  47.60624,
  47.60619,
  47.605617,
  47.605007,
  47.604653,
  47.603998,
  47.603481,
  47.603007,
  47.60211,
  47.600591,
  47.599914,
  47.598612,
  47.597182,
  47.595612,
  47.594808,
  47.594696,
  47.594352,
  47.594283,
  47.594192,
  47.594352,
  47.593901,
  47.593342,
  47.593088,
  47.592774,
  47.592442,
  47.591774,
  47.591646,
  47.591197,
  47.591144,
  47.590931,
  47.59087,
  47.5908,
  47.590546,
  47.590238,
  47.590184,
  47.589944,
  47.58984,
  47.589743,
  47.588735,
  47.588243,
  47.588109,
  47.586752,
  47.584508,
  47.583199,
  47.582569,
  47.582406,
  47.580919,
  47.5801,
  47.578757,
  47.577055,
  47.576591,
  47.576241,
  47.576146,
  47.575339,
  47.575273,
  47.574966,
  47.574009,
  47.573958,
  47.573663,
  47.572506,
  47.572373,
  47.571464,
  47.570898,
  47.570669,
  47.570352,
  47.569694,
  47.569152,
  47.569057,
  47.568242,
  47.567791,
  47.567355,
  47.566796,
  47.566711,
  47.566254,
  47.565807,
  47.565714,
  47.565414,
  47.56524,
  47.565096,
  47.56508,
  47.564919,
  47.564884,
  47.564861,
  47.565031,
  47.564745,
  47.564864,
  47.565043,
  47.564961,
  47.564812,
  47.56441,
  47.563465,
  47.562785,
  47.562532,
  47.562488,
  47.561932,
  47.561873,
  47.561729,
  47.561042,
  47.561008,
  47.560962,
  47.561028,
  47.561037,
  47.560933,
  47.560854,
  47.560753,
  47.56015,
  47.559994,
  47.559931,
  47.557578,
  47.557462,
  47.557318,
  47.557211,
  47.555562,
  47.554799,
  47.55407,
  47.554102,
  47.554197,
  47.55354,
  47.553549,
  47.553557,
  47.553628,
  47.553598,
  47.553451,
  47.5533,
  47.553058,
  47.552099,
  47.551958,
  47.55186,
  47.5518,
  47.551789,
  47.551762,
  47.551213,
  47.551044,
  47.550768,
  47.550653,
  47.550683,
  47.550693,
  47.549977,
  47.549669,
  47.549596,
  47.549143,
  47.54902,
  47.548981,
  47.54878,
  47.548392,
  47.54828,
  47.548167,
  47.547438,
  47.546694,
  47.546455,
  47.546151,
  47.545647,
  47.545448,
  47.545246,
  47.545094,
  47.544471,
  47.544227,
  47.543698,
  47.543626,
  47.543616,
  47.543402,
  47.54298,
  47.542624,
  47.542576,
  47.541891,
  47.54163,
  47.541597,
  47.54155,
  47.54135,
  47.541236,
  47.540887,
  47.540809,
  47.540756,
  47.540717,
  47.540465,
  47.540258,
  47.539967,
  47.539947,
  47.539896,
  47.539857,
  47.539651,
  47.53963,
  47.539615,
  47.539588,
  47.539421,
  47.539112,
  47.538929,
  47.538786,
  47.53873,
  47.538507,
  47.538083,
  47.537424,
  47.536698,
  47.536108,
  47.535231,
  47.534742,
  47.534431,
  47.534186,
  47.534114,
  47.534073,
  47.534026,
  47.533865,
  47.533826,
  47.533345,
  47.533039,
  47.532008,
  47.531959,
  47.53186,
  47.531815,
  47.531783,
  47.531769,
  47.531791,
  47.531813,
  47.53175,
  47.53167,
  47.531728,
  47.531629,
  47.531438,
  47.531143,
  47.529468,
  47.528892,
  47.527635,
  47.527139,
  47.527015,
  47.526578,
  47.526195,
  47.525028,
  47.523691,
  47.523272,
  47.522295,
  47.521161,
  47.520115,
  47.519865,
  47.519042,
  47.517764,
  47.516669,
  47.516624,
  47.516164,
  47.515323,
  47.515262,
  47.515129,
  47.514994,
  47.514856,
  47.514815,
  47.514506,
  47.514405,
  47.5142,
  47.513975,
  47.513964,
  47.513781,
  47.512342,
  47.512163,
  47.512132,
  47.511672,
  47.510276,
  47.510242,
  47.508443,
  47.507774,
  47.507775,
  47.507776,
  47.5077,
  47.507658,
  47.506087,
  47.504863,
  47.504872,
  47.504863,
  47.504752,
  47.503541,
  47.503521,
  47.502236,
  47.50207,
  47.502027,
  47.502009,
  47.50189,
  47.501881,
  47.501632,
  47.500906,
  47.500304,
  47.500102,
  47.500081,
  47.499996,
  47.49986,
  47.499457,
  47.498854,
  47.498756,
  47.498619,
  47.498534,
  47.498385,
  47.498232,
  47.498136,
  47.497991,
  47.497886,
  47.497675,
  47.49754,
  47.497403,
  47.496209,
  47.496189,
  47.496153,
  47.496201,
  47.496207,
  47.496233,
  47.494902,
  47.494512,
  47.493967,
  47.49144,
  47.491397,
  47.490321,
  47.48987,
  47.489823,
  47.48873,
  47.485138,
  47.484989,
  47.484959,
  47.48485,
  47.484811,
  47.484755,
  47.484728,
  47.484565,
  47.484167,
  47.483966,
  47.483947,
  47.483517,
  47.483511,
  47.481903,
  47.480545,
  47.480466,
  47.480448,
  47.48036,
  47.48029,
  47.47915,
  47.478745,
  47.478697,
  47.478616,
  47.478532,
  47.478473,
  47.47842,
  47.478278,
  47.478092,
  47.477938,
  47.477748,
  47.477435,
  47.477161,
  47.47717,
  47.477182,
  47.477161,
  47.477114,
  47.477044,
  47.476977,
  47.476887,
  47.476827,
  47.47679,
  47.476623,
  47.476473,
  47.476432,
  47.476377,
  47.476187,
  47.47616,
  47.476002,
  47.475751,
  47.47563,
  47.475407,
  47.475201,
  47.475139,
  47.475105,
  47.475056,
  47.475026,
  47.474998,
  47.474958,
  47.474331,
  47.474292,
  47.473948,
  47.473652,
  47.473402,
  47.473173,
  47.472868,
  47.472293,
  47.472057,
  47.471599,
  47.470924,
  47.470753,
  47.47061,
  47.470582,
  47.470489,
  47.470184,
  47.470144,
  47.469476,
  47.469363,
  47.469308,
  47.469311,
  47.469504,
  47.469513,
  47.469703,
  47.469719,
  47.46965,
  47.469173,
  47.469142,
  47.468902,
  47.468801,
  47.468701,
  47.468319,
  47.468202,
  47.468096,
  47.468109,
  47.468142,
  47.468173,
  47.468144,
  47.467994,
  47.46788,
  47.467091,
  47.466531,
  47.466399,
  47.466246,
  47.466055,
  47.465826,
  47.46515,
  47.465097,
  47.464527,
  47.464187,
  47.463963,
  47.46376,
  47.463629,
  47.462975,
  47.462908,
  47.462826,
  47.462722,
  47.462671,
  47.46259,
  47.462355,
  47.462258,
  47.462062,
  47.461892,
  47.461868,
  47.461804,
  47.461746,
  47.461614,
  47.461543,
  47.461519,
  47.461447,
  47.459249,
  47.458156,
  47.457562,
  47.457369,
  47.457336,
  47.457293,
  47.457222,
  47.457184,
  47.456286,
  47.455614,
  47.455477,
  47.45544,
  47.455385,
  47.455295,
  47.45519,
  47.454848,
  47.454588,
  47.451314,
  47.451246,
  47.450918,
  47.450587,
  47.450523,
  47.450366,
  47.449749,
  47.448976,
  47.448749,
  47.448392,
  47.44835,
  47.447883,
  47.447776,
  47.44772,
  47.445644,
  47.443955,
  47.443849,
  47.44377,
  47.441116,
  47.441111,
  47.441103,
  47.441019,
  47.440925,
  47.440955,
  47.440933,
  47.440913,
  47.440905,
  47.440903,
  47.440914,
  47.440944,
  47.440876,
  47.440858,
  47.440784,
  47.440645,
  47.440632,
  47.440627,
  47.440627,
  47.437737,
  47.43588,
  47.435667,
  47.434071,
  47.431592,
  47.431502,
  47.430876,
  47.430796,
  47.430691,
  47.430605,
  47.430298,
  47.430271,
  47.430397,
  47.430363,
  47.430291,
  47.43018,
  47.429914,
  47.429868,
  47.428463,
  47.428149,
  47.427682,
  47.426946,
  47.426851,
  47.426414,
  47.42604,
  47.425026,
  47.423522,
  47.419992,
  47.418259,
  47.417206,
  47.416068,
  47.414967,
  47.414229,
  47.413998,
  47.413617,
  47.413452,
  47.413349,
  47.41331,
  47.412904,
  47.41275,
  47.412786,
  47.412712,
  47.411663,
  47.411441,
  47.410515,
  47.4102,
  47.409621,
  47.409204,
  47.408893,
  47.408863,
  47.409143,
  47.408618,
  47.408355,
  47.408348,
  47.407386,
  47.407201,
  47.407047,
  47.40698,
  47.406671,
  47.406347,
  47.405646,
  47.405478,
  47.4053,
  47.405141,
  47.405207,
  47.40506,
  47.404977,
  47.403765,
  47.403607,
  47.401898,
  47.401519,
  47.401185,
  47.40089,
  47.400647,
  47.400512,
  47.400432,
  47.400241,
  47.400143,
  47.399824,
  47.399637,
  47.399238,
  47.39882,
  47.396097,
  47.395749,
  47.394825,
  47.394658,
  47.394457,
  47.394391,
  47.392877,
  47.385821,
  47.384912,
  47.384166,
  47.384041,
  47.384103,
  47.384052,
  47.383668,
  47.383311,
  47.38325,
  47.38318,
  47.383089,
  47.382801,
  47.382742,
  47.382409,
  47.381823,
  47.381193,
  47.380888,
  47.380324,
  47.380136,
  47.379808,
  47.379703,
  47.379641,
  47.378937,
  47.378472,
  47.378354,
  47.377991,
  47.37758,
  47.377141,
  47.377071,
  47.377026,
  47.376838,
  47.376579,
  47.376635,
  47.376423,
  47.37605,
  47.375264,
  47.374851,
  47.374133,
  47.373511,
  47.373038,
  47.372993,
  47.372491,
  47.372235,
  47.371886,
  47.371791,
  47.371232,
  47.371017,
  47.370875,
  47.37073,
  47.370522,
  47.369447,
  47.3684,
  47.368142,
  47.368136,
  47.368028,
  47.368003,
  47.367746,
  47.367268,
  47.366661,
  47.36612,
  47.365702,
  47.365211,
  47.365181,
  47.365063,
  47.364241,
  47.364076,
  47.363549,
  47.362932,
  47.362272,
  47.362032,
  47.361478,
  47.361241,
  47.360924,
  47.359871,
  47.359291,
  47.358936,
  47.358248,
  47.358188,
  47.357954,
  47.357497,
  47.356924,
  47.356845,
  47.356566,
  47.356087,
  47.355965,
  47.35533,
  47.355024,
  47.354635,
  47.353806,
  47.353257,
  47.352821,
  47.352432,
  47.352017,
  47.352001,
  47.351769,
  47.351539,
  47.349374,
  47.349148,
  47.349006,
  47.347872,
  47.34695,
  47.346786,
  47.346722,
  47.34583,
  47.345101,
  47.344249,
  47.34375,
  47.343065,
  47.341551,
  47.341017,
  47.340859,
  47.340343,
  47.339779,
  47.339664,
  47.339441,
  47.339356,
  47.339311,
  47.339195,
  47.339153,
  47.339089,
  47.339005,
  47.3388,
  47.337781,
  47.337627,
  47.336712,
  47.336554,
  47.336025,
  47.336045,
  47.335848,
  47.335726,
  47.335137,
  47.33506,
  47.334966,
  47.334868,
  47.334861,
  47.334795,
  47.334575,
  47.334101,
  47.333961,
  47.333822,
  47.333679,
  47.333298,
  47.333185,
  47.333095,
  47.33308,
  47.333016,
  47.332797,
  47.332417,
  47.332201,
  47.33187,
  47.331407,
  47.330933,
  47.330362,
  47.330265,
  47.33023,
  47.330045,
  47.329924,
  47.329775,
  47.329739,
  47.329658,
  47.329489,
  47.329382,
  47.329334,
  47.329335,
  47.329296,
  47.328265,
  47.326788,
  47.325748,
  47.325172,
  47.325105,
  47.324662,
  47.32426,
  47.323852,
  47.322437,
  47.321103,
  47.321179,
  47.321283,
  47.321308,
  47.321309,
  47.320462,
  47.319838,
  47.318284,
  47.318183,
  47.318074,
  47.317829,
  47.315888,
  47.315806,
  47.315447,
  47.315173,
  47.314429,
  47.314267,
  47.314027,
  47.313551,
  47.311985,
  47.311447,
  47.311157,
  47.310839,
  47.310489,
  47.310273,
  47.309706,
  47.309151,
  47.308599,
  47.308024,
  47.30724,
  47.306762,
  47.30607,
  47.306341,
  47.305908,
  47.305427,
  47.304268,
  47.303886,
  47.303697,
  47.303333,
  47.301666,
  47.301094,
  47.30054,
  47.300079,
  47.299329,
  47.298365,
  47.298223,
  47.297077,
  47.295822,
  47.293676,
  47.292662,
  47.289888,
  47.287851,
  47.287126,
  47.286131,
  47.285694,
  47.285402,
  47.282209,
  47.278802,
  47.274999,
  47.274481,
  47.274417,
  47.273264,
  47.273109,
  47.272199,
  47.271325,
  47.269536,
  47.268027,
  47.264475,
  47.264296,
  47.264123,
  47.260755,
  47.260276,
  47.259927,
  47.259231,
  47.258859,
  47.258092,
  47.253175,
  47.249699,
  47.248764,
  47.248556,
  47.247991,
  47.247418,
  47.245429,
  47.243738,
  47.243076,
  47.241063,
  47.240732,
  47.239192,
  47.236825,
  47.236613,
  47.235803,
  47.235659,
  47.232507,
  47.231964,
  47.231439,
  47.230428,
  47.230317,
  47.230257,
  47.229874,
  47.22982,
  47.229476,
  47.229288,
  47.229103,
  47.229088,
  47.229014,
  47.22897,
  47.228925,
  47.228882,
  47.228614,
  47.228497,
  47.228291,
  47.227521,
  47.227491,
  47.227473,
  47.227408,
  47.226909,
  47.226849,
  47.226664,
  47.226625,
  47.226588,
  47.226559,
  47.226379,
  47.226002,
  47.224195,
  47.223043,
  47.221806,
  47.220649,
  47.219627,
  47.218888,
  47.21842,
  47.217593,
  47.216112,
  47.215785,
  47.21574,
  47.215735,
  47.215727,
  47.215675,
  47.215621,
  47.215465,
  47.215432,
  47.215279,
  47.213737,
  47.212202,
  47.212117,
  47.210621,
  47.209238,
  47.208391,
  47.207287,
  47.206353,
  47.204462,
  47.204182,
  47.204132,
  47.204171,
  47.203471,
  47.203118,
  47.20209,
  47.200339,
  47.199204,
  47.198353,
  47.197972,
  ...],
 [19.079729,
  19.080162,
  19.082329,
  19.082461,
  19.082412,
  19.081553,
  19.081456,
  19.081376,
  19.081385,
  19.081433,
  19.081679,
  19.082629,
  19.08277,
  19.082885,
  19.083127,
  19.083079,
  19.082926,
  19.082629,
  19.082855,
  19.084711,
  19.085317,
  19.086321,
  19.087257,
  19.08857,
  19.089172,
  19.089322,
  19.089754,
  19.089875,
  19.0896,
  19.089686,
  19.089214,
  19.088759,
  19.087016,
  19.086759,
  19.086572,
  19.086239,
  19.086028,
  19.085702,
  19.085347,
  19.085193,
  19.084999,
  19.084489,
  19.08435,
  19.084271,
  19.084074,
  19.084002,
  19.083644,
  19.083436,
  19.082989,
  19.082628,
  19.082425,
  19.082343,
  19.082234,
  19.082179,
  19.082102,
  19.081712,
  19.080899,
  19.080688,
  19.080303,
  19.079864,
  19.079847,
  19.079739,
  19.079645,
  19.07913,
  19.078846,
  19.07881,
  19.077686,
  19.077609,
  19.077106,
  19.076988,
  19.076978,
  19.076954,
  19.07692,
  19.076557,
  19.076201,
  19.076016,
  19.075692,
  19.075223,
  19.07491,
  19.074953,
  19.07526,
  19.075232,
  19.075142,
  19.074858,
  19.074702,
  19.074426,
  19.074384,
  19.07398,
  19.073441,
  19.073147,
  19.072594,
  19.072245,
  19.071978,
  19.071476,
  19.070658,
  19.070392,
  19.070131,
  19.069958,
  19.069921,
  19.069907,
  19.069789,
  19.069309,
  19.069169,
  19.068966,
  19.06681,
  19.066696,
  19.066518,
  19.066438,
  19.066341,
  19.06623,
  19.066008,
  19.065965,
  19.065828,
  19.065812,
  19.06575,
  19.065732,
  19.065713,
  19.065647,
  19.065598,
  19.065592,
  19.065564,
  19.065552,
  19.065544,
  19.065432,
  19.065377,
  19.065355,
  19.065203,
  19.064929,
  19.064775,
  19.064684,
  19.064647,
  19.064283,
  19.064088,
  19.063734,
  19.063151,
  19.062996,
  19.062875,
  19.062842,
  19.062593,
  19.062573,
  19.062609,
  19.062365,
  19.062349,
  19.062273,
  19.061957,
  19.061934,
  19.06179,
  19.061713,
  19.061694,
  19.06166,
  19.061609,
  19.061569,
  19.061564,
  19.06158,
  19.061581,
  19.061597,
  19.061615,
  19.061613,
  19.06163,
  19.061523,
  19.061501,
  19.061429,
  19.061388,
  19.061353,
  19.06135,
  19.061311,
  19.061288,
  19.060936,
  19.05943,
  19.059226,
  19.05828,
  19.056885,
  19.056172,
  19.055723,
  19.05488,
  19.054168,
  19.053782,
  19.053643,
  19.053618,
  19.053313,
  19.05328,
  19.053204,
  19.052836,
  19.05277,
  19.052673,
  19.052396,
  19.052369,
  19.052274,
  19.052229,
  19.052204,
  19.05189,
  19.051805,
  19.051771,
  19.050453,
  19.050387,
  19.05032,
  19.050295,
  19.049448,
  19.04905,
  19.048648,
  19.048471,
  19.046788,
  19.046482,
  19.046403,
  19.046308,
  19.045318,
  19.045274,
  19.045268,
  19.045352,
  19.045513,
  19.046234,
  19.04634,
  19.046369,
  19.046196,
  19.046167,
  19.046177,
  19.046611,
  19.046639,
  19.046611,
  19.046603,
  19.046172,
  19.046023,
  19.045851,
  19.045812,
  19.045804,
  19.045742,
  19.045724,
  19.045717,
  19.045694,
  19.045639,
  19.045629,
  19.045619,
  19.045504,
  19.045397,
  19.045352,
  19.045301,
  19.045262,
  19.045367,
  19.045543,
  19.045603,
  19.045629,
  19.045633,
  19.045664,
  19.045727,
  19.045724,
  19.045699,
  19.045646,
  19.045618,
  19.045636,
  19.045852,
  19.045586,
  19.045488,
  19.04536,
  19.045337,
  19.045348,
  19.045402,
  19.045405,
  19.0454,
  19.045395,
  19.045369,
  19.045344,
  19.045351,
  19.045385,
  19.045378,
  19.04538,
  19.046135,
  19.046364,
  19.046414,
  19.046465,
  19.046824,
  19.046864,
  19.046869,
  19.046846,
  19.04683,
  19.046944,
  19.046933,
  19.046834,
  19.046474,
  19.046066,
  19.045358,
  19.044864,
  19.044556,
  19.044331,
  19.044266,
  19.044232,
  19.044188,
  19.044032,
  19.044048,
  19.04357,
  19.043257,
  19.042361,
  19.042265,
  19.042226,
  19.0422,
  19.042305,
  19.04241,
  19.042495,
  19.042515,
  19.04272,
  19.043129,
  19.043499,
  19.043574,
  19.043581,
  19.043425,
  19.042148,
  19.041704,
  19.040939,
  19.040665,
  19.040614,
  19.040276,
  19.040162,
  19.039556,
  19.038979,
  19.038767,
  19.038549,
  19.038453,
  19.038522,
  19.038626,
  19.038772,
  19.039144,
  19.039436,
  19.039448,
  19.039576,
  19.039803,
  19.039817,
  19.03984,
  19.039859,
  19.039795,
  19.039793,
  19.03981,
  19.039792,
  19.039759,
  19.039784,
  19.039787,
  19.039737,
  19.039478,
  19.039487,
  19.039486,
  19.039435,
  19.039399,
  19.039407,
  19.039426,
  19.039429,
  19.039334,
  19.039258,
  19.039256,
  19.039261,
  19.039289,
  19.039378,
  19.039579,
  19.03958,
  19.039592,
  19.039735,
  19.039738,
  19.039955,
  19.039991,
  19.039773,
  19.039691,
  19.039101,
  19.039056,
  19.039157,
  19.039457,
  19.039729,
  19.039814,
  19.039822,
  19.039855,
  19.039908,
  19.040053,
  19.040273,
  19.040286,
  19.040304,
  19.040281,
  19.040137,
  19.040184,
  19.040389,
  19.040578,
  19.040671,
  19.040751,
  19.040834,
  19.04094,
  19.042007,
  19.042023,
  19.042053,
  19.042241,
  19.042267,
  19.042369,
  19.043111,
  19.043427,
  19.043884,
  19.045968,
  19.046005,
  19.047058,
  19.047596,
  19.047644,
  19.048842,
  19.052733,
  19.052843,
  19.052875,
  19.052995,
  19.053045,
  19.053115,
  19.053148,
  19.05332,
  19.05382,
  19.054058,
  19.05408,
  19.054579,
  19.054586,
  19.056377,
  19.057933,
  19.058016,
  19.058035,
  19.058114,
  19.05818,
  19.059453,
  19.059871,
  19.059828,
  19.059747,
  19.059847,
  19.059919,
  19.059979,
  19.059909,
  19.059463,
  19.05921,
  19.059074,
  19.059152,
  19.059391,
  19.05945,
  19.059583,
  19.059605,
  19.059654,
  19.059727,
  19.059797,
  19.059881,
  19.059757,
  19.059686,
  19.059343,
  19.059291,
  19.059234,
  19.05912,
  19.058547,
  19.058339,
  19.057996,
  19.057471,
  19.057239,
  19.056771,
  19.056418,
  19.056377,
  19.056273,
  19.056101,
  19.055986,
  19.056005,
  19.056032,
  19.056421,
  19.056496,
  19.056652,
  19.056697,
  19.056645,
  19.056505,
  19.056165,
  19.054989,
  19.054504,
  19.053902,
  19.053392,
  19.053303,
  19.053239,
  19.053227,
  19.053194,
  19.053096,
  19.053008,
  19.052974,
  19.052974,
  19.052972,
  19.052945,
  19.051944,
  19.051897,
  19.050909,
  19.050837,
  19.050775,
  19.050621,
  19.050562,
  19.050492,
  19.050545,
  19.05059,
  19.05047,
  19.050346,
  19.050271,
  19.050186,
  19.049962,
  19.049757,
  19.049717,
  19.049674,
  19.049732,
  19.049456,
  19.049258,
  19.049222,
  19.04914,
  19.049067,
  19.048994,
  19.04878,
  19.048766,
  19.048605,
  19.048495,
  19.048521,
  19.048466,
  19.048412,
  19.048197,
  19.048177,
  19.048154,
  19.048119,
  19.048107,
  19.048084,
  19.048016,
  19.047988,
  19.047906,
  19.047894,
  19.047888,
  19.047912,
  19.047927,
  19.047918,
  19.047898,
  19.047913,
  19.047974,
  19.047282,
  19.046762,
  19.046586,
  19.046618,
  19.046613,
  19.046602,
  19.046602,
  19.046492,
  19.046295,
  19.046037,
  19.04588,
  19.045918,
  19.045974,
  19.04595,
  19.045922,
  19.045791,
  19.045599,
  19.044553,
  19.044534,
  19.04447,
  19.044504,
  19.044486,
  19.04422,
  19.044035,
  19.043793,
  19.043723,
  19.043611,

#!pip install folium

import folium


route_map = folium.Map(
    location=[45, 25.3],
    zoom_start=5,
    tiles='OpenStreetMap',
    width=1024,
    height=600
)

coordinates = [tuple(x) for x in route_df[['latitude', 'longitude']].to_numpy()]
folium.PolyLine(coordinates, weight=6).add_to(route_map)

display(route_map)

In [6]:
import geojson
with open('./HU-GR_geojson/tracks.geojson') as f:
    gj = geojson.load(f)

In [10]:
m = folium.Map(location=[40.66393072,-73.93827499], zoom_start=13)

m.choropleth(open("./HU-GR_geojson/tracks.geojson"))

ValueError: Cannot render objects with any missing geometries: <_io.TextIOWrapper name='./HU-GR_geojson/tracks.geojson' mode='r' encoding='UTF-8'>

### Routes (+1) plots with Folium and OpenStreetMaps

#### Load the different routes

In [7]:
with open('My_Routes/PL-SK-HU.gpx', 'r') as gpx_file:
    gpx = gpxpy.parse(gpx_file)

route_info = []

for track in gpx.tracks:
    for segment in track.segments:
        for point in segment.points:
            route_info.append({
                'latitude': point.latitude,
                'longitude': point.longitude,
                'elevation': point.elevation
            })

route_df_y22 = pd.DataFrame(route_info)

route_df_y22['Performed'] = 'Y22'


route_df_y22.head(2)

    latitude  longitude   elevation Performed
0  49.864104  19.109029  386.362446       Y22
1  49.864275  19.109137  386.362446       Y22

In [11]:
with open('HU-GR_gpx/HU-GR.gpx', 'r') as gpx_file:
    gpx = gpxpy.parse(gpx_file)

route_info = []

for track in gpx.tracks:
    for segment in track.segments:
        for point in segment.points:
            route_info.append({
                'latitude': point.latitude,
                'longitude': point.longitude,
                'elevation': point.elevation
            })

route_df_y24 = pd.DataFrame(route_info)

route_df_y24['Performed'] = 'Y24'

route_df_y24.head(2)

    latitude  longitude   elevation Performed
0  47.634836  19.079729  101.675182       Y24
1  47.634213  19.080162  101.675182       Y24

In [12]:
route_map = folium.Map(
    location=[47, 32],
    zoom_start=5,
    tiles='OpenStreetMap',
    width=924,
    height=600
)

coordinates = [tuple(x) for x in route_df_y22[['latitude', 'longitude']].to_numpy()]
folium.PolyLine(coordinates, weight=3,color='green').add_to(route_map)
folium.LayerControl().add_to(route_map)

coordinates = [tuple(x) for x in route_df_y24[['latitude', 'longitude']].to_numpy()]
folium.PolyLine(coordinates, weight=3, color='gray').add_to(route_map)
folium.LayerControl().add_to(route_map)

display(route_map)

#route_map.save('./output_map.html')

#### Defining the functions for multi-route

In [38]:
# import gpxpy
# import pandas as pd
# import folium

def plot_routes_on_map(gpx_paths, colors):
    route_data = []
    for gpx_path, color in zip(gpx_paths, colors):
        with open(gpx_path, 'r') as gpx_file:
            gpx = gpxpy.parse(gpx_file)
            for track in gpx.tracks:
                for segment in track.segments:
                    for point in segment.points:
                        route_data.append({
                            'latitude': point.latitude,
                            'longitude': point.longitude,
                            'elevation': point.elevation,
                            'color': color
                        })

    route_df = pd.DataFrame(route_data)

    route_map = folium.Map(
        location=[50, 23],
        zoom_start=7,
        tiles='OpenStreetMap',
        #tiles='Stamen Toner',
        #tiles="Stamen Terrain",
        #tiles="Stamen Watercolor",
        width=924,
        height=600
    )

    for color, route_df_group in route_df.groupby('color'):
        coordinates = [tuple(x) for x in route_df_group[['latitude', 'longitude']].to_numpy()]
        folium.PolyLine(coordinates, weight=3, color=color).add_to(route_map)

    folium.LayerControl().add_to(route_map)

    return route_map

In [39]:
route_map = plot_routes_on_map(['My_Routes/Krakow - Zarki.gpx',
                                'My_Routes/Zarki - Czestochowa.gpx'], ['#027835',
                                                                       '#027835'])
display(route_map)

In [40]:
route_map.save('Map-KrakowCzestochowa.html')

In [12]:
route_map = plot_routes_on_map(['My_Routes/PL-SK-HU.gpx',
                                'My_Routes/Krakow - Zarki.gpx',
                                'My_Routes/Zarki - Czestochowa.gpx'], ['green', 
                                                                       '#027835',
                                                                       '#027835'])
display(route_map)

In [17]:
route_map.save('Map-CyclingThroughEurope-APR23.html')

In [8]:
def plot_routes_on_map_markers(gpx_paths, colors, markers=[]):
    route_data = []
    for gpx_path, color in zip(gpx_paths, colors):
        with open(gpx_path, 'r') as gpx_file:
            gpx = gpxpy.parse(gpx_file)
            for track in gpx.tracks:
                for segment in track.segments:
                    for point in segment.points:
                        route_data.append({
                            'latitude': point.latitude,
                            'longitude': point.longitude,
                            'elevation': point.elevation,
                            'color': color
                        })

    route_df = pd.DataFrame(route_data)

    route_map = folium.Map(
        location=[47, 32],
        zoom_start=5,
        tiles='OpenStreetMap',
        width=924,
        height=600
    )

    for color, route_df_group in route_df.groupby('color'):
        coordinates = [tuple(x) for x in route_df_group[['latitude', 'longitude']].to_numpy()]
        folium.PolyLine(coordinates, weight=3, color=color).add_to(route_map)

    for marker in markers:
        folium.Marker(location=[marker['lat'], marker['lon']], popup=marker['name']).add_to(route_map)

    folium.LayerControl().add_to(route_map)

    return route_map

In [9]:
markers = [{'lat': 50, 'lon': 20, 'name': 'Marker 1'},
           {'lat': 55, 'lon': 25, 'name': 'Marker 2'}]

route_map = plot_routes_on_map_markers(['My_Routes/PL-SK-HU.gpx', 'HU-GR_gpx/HU-GR.gpx'],
                                       ['green', 'gray'],
                                       markers=markers)
display(route_map)